apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-cert-acm.fullname" . }}
  labels:
    {{- include "kube-cert-acm.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - get
- apiGroups:
    - "cert-manager.io"
  resources:
    - certificates
  verbs:
    - get
